// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Domain;

#nullable disable

namespace Test.Migrations
{
    [DbContext(typeof(PriceContext))]
    [Migration("20240720114257__initial")]
    partial class _initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ColumnPriceList", b =>
                {
                    b.Property<int>("ColumnsId")
                        .HasColumnType("int");

                    b.Property<int>("priceListsId")
                        .HasColumnType("int");

                    b.HasKey("ColumnsId", "priceListsId");

                    b.HasIndex("priceListsId");

                    b.ToTable("ColumnPriceList");
                });

            modelBuilder.Entity("DescriptionProduct", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("descriptionsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "descriptionsId");

                    b.HasIndex("descriptionsId");

                    b.ToTable("DescriptionProduct");
                });

            modelBuilder.Entity("PriceListProduct", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("priceListsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "priceListsId");

                    b.HasIndex("priceListsId");

                    b.ToTable("PriceListProduct");
                });

            modelBuilder.Entity("Test.Domain.Entites.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Columns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = "Текст",
                            Name = "Название товара"
                        },
                        new
                        {
                            Id = 2,
                            DataType = "Число",
                            Name = "Код товара"
                        });
                });

            modelBuilder.Entity("Test.Domain.Entites.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("descriptionNumber")
                        .HasColumnType("int");

                    b.Property<string>("descriptionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("descriptions");
                });

            modelBuilder.Entity("Test.Domain.Entites.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("priceLists");
                });

            modelBuilder.Entity("Test.Domain.Entites.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("articleNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ColumnPriceList", b =>
                {
                    b.HasOne("Test.Domain.Entites.Column", null)
                        .WithMany()
                        .HasForeignKey("ColumnsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.Entites.PriceList", null)
                        .WithMany()
                        .HasForeignKey("priceListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DescriptionProduct", b =>
                {
                    b.HasOne("Test.Domain.Entites.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.Entites.Description", null)
                        .WithMany()
                        .HasForeignKey("descriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PriceListProduct", b =>
                {
                    b.HasOne("Test.Domain.Entites.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Domain.Entites.PriceList", null)
                        .WithMany()
                        .HasForeignKey("priceListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
