// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Domain;

#nullable disable

namespace Test.Migrations
{
    [DbContext(typeof(PriceContext))]
    partial class PriceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Test.Domain.Entites.Column", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriceListid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PriceListid");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Test.Domain.Entites.PriceList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("priceLists");
                });

            modelBuilder.Entity("Test.Domain.Entites.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("priceListid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("priceListid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Test.Domain.Entites.Column", b =>
                {
                    b.HasOne("Test.Domain.Entites.PriceList", null)
                        .WithMany("Columns")
                        .HasForeignKey("PriceListid");
                });

            modelBuilder.Entity("Test.Domain.Entites.Product", b =>
                {
                    b.HasOne("Test.Domain.Entites.PriceList", "priceList")
                        .WithMany()
                        .HasForeignKey("priceListid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("priceList");
                });

            modelBuilder.Entity("Test.Domain.Entites.PriceList", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
